const words_list=[
'Pizza party',
'Movie night',
'Red dot',
'Moonwalk',
'Starfish',
'Sunflower',
'Fireball',
'Time machine',
'Rockstar',
'Waterfall',
'Stardust',
'Firefly',
'Thunderbolt',
'Windchime',
'Firestorm',
'Starlight',
'Earthquake',
'Snow fight',
'Lady bug',
'Fire dance',
'Spacewalk',
'Game night',
'Game show',
'Lemon tree',
'Traffic jam',
'Garden party',
'Tea time',
'Secret handshake',
'Birthday wish',
'Pillow talk',
'Tree house',
'Free fall',
'dragon ball',
'one piece',
'Salty fish',
'Cat nap',
'Pillow talk',
'Sunshine',
'Bonfire',
'Lighthouse',
'Jellybean',
'Breaking bad',
'Time jump',
'Dead walking',
'Phone call',
'Chicken dinner',
'Sweet victory',
'Surprise party',
'Ghost house',
'Football club',
'Basketball court',
'Spicy food',
'Fast food',
'Dining table',
'Washing machine',
'Hot chocolate',
'Running shoes',
'tomb raider',
'Home alone',
'Family guy',
'Small talk',
'Silent night',
'Game of thrones',
'Icy tower',
'Ghost story',
'Treasure chest',
'Night club',
'Sleepwalking',
'Cloud 9',
'Time travel',
'Smashed potato',
'High hopes',
'Stock market',
'Scary movie',
'Hot water',
'Happy hour',
'Honeymoon',
'Water gun',
]

export default words_list;